load("@buildifier_prebuilt//:rules.bzl", "buildifier")
load("//tools/lint/bazel:index.bzl", "bzl_lint_test")

buildifier(
    name = "buildifier",
    exclude_patterns = [
        "./bazel-*/*",
    ],
)

bzl_lint_test(
    name = "root_bzl_lint_test",
    data = glob(
        [
            "*.bazel",
            "*.bzl",
        ],
        allow_empty = True,
    ),
)
