name: Docker Build

on:
  workflow_dispatch:
    paths:
      - ".github/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/**"

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Build
        run: docker build .github
